server:
    port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cumt-cx/spring-boot-cloud-sandwich.git
          searchPaths: bootcloudprj-config-repo